name: ⚙️ autofix

on:
  push:
  schedule:
    - cron: '55 5 * * *'
  workflow_dispatch:

jobs:
  autofix:
    runs-on: Ubuntu-20.04
    name: ⚙️ autofix
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: '1'
      - run: deno fmt
      - name: Check for Changes
        id: check
        run: |
          git status
          declare had_changes="$(
            [[ -n "$(git status --porcelain)" ]] && echo true || echo false
          )"
          echo "::set-output name=had-changes::${had_changes}"
      - name: Push Any Changes
        if: steps.check.outputs.had-changes == 'true'
        run: |
          declare br="
          "
          declare branch="$(echo ${GITHUB_REF#refs/heads/})"
          declare short_hash="$(git rev-parse --short=8 HEAD)"
          declare short_subject="$(git log -1 --pretty=format:'%s')"
          declare short_subject="$(git log -1 --pretty=format:'%s')"
          if [[ ${#short_subject} -gt 50 ]]; then
            short_subject="${short_subject:0:49}…"
          fi
          declare author_name="$(git log -1 --pretty=format:'%an')"
          declare author_email="$(git log -1 --pretty=format:'%ae')"
          declare date="$(git log -1 --pretty=format:'%cd')"
          declare current_action_url="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${{ github.run_id }}"
          export GIT_AUTHOR_DATE="${date}"
          export GIT_AUTHOR_NAME="${author_name}"
          export GIT_AUTHOR_EMAIL="${author_email}"
          export GIT_COMMITTER_DATE="${date}"
          export GIT_COMMITTER_NAME="autofix"
          export GIT_COMMITTER_EMAIL="autofix@jeremy.ca"
          git remote rm origin
          git remote add origin "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git checkout "${branch}"
          git add .
          git commit -m "⚙️ autofix ${short_hash} (${short_subject})${br}${br}${current_action_url}"
          git push --force origin HEAD:"${branch}-autofix"
          git push --set-upstream origin "${branch}"
